# Generated by Django 5.1.6 on 2025-03-10 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('show_lang', models.CharField(default='', max_length=30)),
                ('version', models.IntegerField(default=1)),
                ('show_language_icon', models.BinaryField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keys', models.CharField(max_length=100)),
                ('values', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.languagemodel')),
            ],
        ),
    ]
